// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1666321970);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1666321940);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{58246574-0f66-4c18-955b-ac9c8a0da656}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 5);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.homepage_override.buildID", "20220607050101");
user_pref("browser.startup.homepage_override.mstone", "91.13.0");
user_pref("browser.startup.homepage_override.torbrowser.version", "11.5.4");
user_pref("browser.startup.lastColdStartupCheck", 1666322158);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"torbutton-button\",\"security-level-button\",\"new-identity-button\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"PanelUI-contents\":[\"home-button\",\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"save-page-button\",\"print-button\",\"bookmarks-menu-button\",\"history-panelmenu\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"]},\"seen\":[\"developer-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":17,\"currentTorVersion\":1,\"newElementCount\":1}");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "91.13.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220607050101");
user_pref("extensions.lastAppVersion", "91.13.0");
user_pref("extensions.lastPlatformVersion", "91.13.0");
user_pref("extensions.lastTorBrowserVersion", "11.5.4");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.torbutton.cookiejar_migrated", true);
user_pref("extensions.torbutton.noscript_inited", true);
user_pref("extensions.torbutton.pref_fixup_version", 1);
user_pref("extensions.torbutton.security_slider_migration", 2);
user_pref("extensions.torbutton.startup", true);
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.torlauncher.should_remove_meek_helper_profiles", false);
user_pref("extensions.torlauncher.torrc_fixup_version", 2);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"e3195e63-79d5-43c8-8b00-e5156bc400bb\",\"onboarding@mozilla.org\":\"e1ed92e3-ba52-4955-b0de-09708e23f6b9\",\"default-theme@mozilla.org\":\"cc601010-c1ef-4661-8cfc-51eb1c9ba665\",\"ddg@search.mozilla.org\":\"af28f0f5-4aa2-4042-9b9d-6142587ec490\",\"youtube@search.mozilla.org\":\"373a6177-ae9b-446b-a8b9-01d6d4fcf0c3\",\"google@search.mozilla.org\":\"ece54f96-0e8e-4191-a01e-d1c009ecff71\",\"blockchair@search.mozilla.org\":\"ed8450d5-c94a-4e71-8d13-8ec7158ff2b2\",\"ddg-onion@search.mozilla.org\":\"8fbb26fd-6ae2-4115-ab4e-514305542b05\",\"startpage@search.mozilla.org\":\"7898013e-0233-4173-a0ca-cc2401ef0281\",\"twitter@search.mozilla.org\":\"b9772176-f44d-4211-8a5f-d538f361c257\",\"wikipedia@search.mozilla.org\":\"7a05f237-4e30-4e88-b429-cc8347787c42\",\"yahoo@search.mozilla.org\":\"a2441b19-0fe0-4592-9288-0d2f65e9737c\"}");
user_pref("media.gmp-manager.buildID", "20220607050101");
user_pref("media.gmp-manager.lastCheck", 1666321966);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.enabled", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "643e7f8d-5d36-4145-a1b4-2c60cca30f5d");
user_pref("toolkit.startup.last_success", 1666322156);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("torbrowser.settings.bridges.builtin_type", "");
user_pref("torbrowser.settings.bridges.enabled", false);
user_pref("torbrowser.settings.bridges.source", -1);
user_pref("torbrowser.settings.enabled", true);
user_pref("torbrowser.settings.firewall.enabled", false);
user_pref("torbrowser.settings.proxy.enabled", false);
user_pref("torbrowser.settings.quickstart.enabled", true);
